apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: project2-exists-pr
  namespace: acmconf
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []

