apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multiapp
  name: multiapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiapp
  template:
    metadata:
      labels:
        app: multiapp
    spec:
      containers:
      - image: quay.io/apoczeka/fractal:latest
        name: multiapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"

