apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceReplicaSet
metadata:
  labels:
    app: multiapp
  name: multiapp-vms
spec:
  replicas: 2
  selector:
    matchLabels:
      myvmi: multiapp
  template:
    metadata:
      name: multiapp
      labels:
        myvmi: multiapp
        app: multiapp
    spec:
      domain:
        devices:
          disks:
          - disk:
            name: containerdisk
        resources:
          requests:
            memory: 128M
            cpu: 1000m
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/apoczeka/vm:latest
