apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app1
  namespace: app1
spec:
  selector:
    matchExpressions:
      - key: deployment  
        operator: In
        values:
        - app1
  componentKinds:
  - group: apps.open-cluster-management.io/v1
    kind: Subscription
