apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: web-app     
  namespace: app1
spec:
  selector:
    matchExpressions:
      - key: deployment  
        operator: In
        values:
        - hello 
  componentKinds:
  - group: apps.open-cluster-management.io/v1
    kind: Subscription
