apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: app1
  namespace: app1
  labels:
    deployment: app1
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: common-managed/apps/app1/
spec:
  channel: app1-ch/git1
  placement: 
    placementRef: 
      kind: PlacementRule
      name: localcluster
