apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: web-app-localcluster
  namespace: app1
  labels:
    deployment: hello
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: 2/assets/overlays/cluster1
spec:
  channel: demo-acm-2-ch/git1
  placement: 
    placementRef: 
      kind: PlacementRule
      name: localcluster
