apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app1
  namespace: app1
  labels:
    app: acmconf
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - app1
