apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acmconf
  namespace: acmconf
  labels:
    app: acmconf
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
        - acmconf

