apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acmconf
  labels: 
    app: acmconf
  namespace: acmconf
  annotations:
    apps.open-cluster-management.io/current-namespace-scoped: "false"
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: managed-subscriptions
spec:
  channel: acmconf-ch/acmconf
  placement:
    clusters:
      name: "local-cluster"
